### PR TITLE
Add reload extension and isBotAdmin

### PR DESCRIPTION
**Pull request by sydneyq**
hi kirollos 🦄 

here's a simple function for bot admin check and a reload extension cmd that I found useful when testing stuff on my own bot

### CODE REVIEW

**Review by Anarav — CHANGES_REQUESTED** [review]
Great addition, thank you!

I would suggest changing the method name to `is_bot_admin` to just keep it consistent with the rest of the code base

**Review by Kironb — CHANGES_REQUESTED** [review]
It seems like a great idea, we wanted to change the admin check soon too.
I am unsure if self.BotAdmin(user_id) is going to work since we do not have a self in these functions,
could you change it to isBotAdmin(user_id) instead?

**Comment by sydneyq** [comment]
Changes added!

**Comment by sydneyq** [comment]
Changes added!

**Comment by Kironb** [comment]
Thank you!

**Pull request merged**
